In [5]:
# IMPORTS
import config
import random as rd
import config
from init_pop import Init_Pop
from fitness import Fitness_Function
from mutation import Mutation
from recombination import Recombination
from survival_selection import Survival_Selection
from parent_selection import Parent_Selection
from termination import Termination
from visuals import Visualization
import numpy as np

In [6]:
init_obj = Init_Pop('random')
population = init_obj(config.GENOME_SIZE, config.POPULATION_SIZE)

In [7]:
population.shape

(100, 8)

In [8]:
population[:5]

array([[5, 3, 3, 6, 4, 5, 4, 7],
       [5, 2, 5, 3, 6, 5, 7, 7],
       [2, 7, 7, 6, 2, 4, 1, 4],
       [2, 1, 4, 3, 3, 5, 3, 6],
       [1, 8, 6, 8, 2, 5, 6, 3]])

In [9]:
fitness = Fitness_Function('conflict_based')

UnboundLocalError: cannot access local variable 'fitness_strategies' where it is not associated with a value

In [6]:
fitness_vals = fitness(population, config.GENOME_SIZE)

In [7]:
print(min(fitness_vals))
print(max(fitness_vals))

0.4285714285714286
0.9285714285714286


In [8]:
np.arange(1, 10+1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.random.choice(a=np.arange(1, 10+1), size=3, replace=False)

array([2, 7, 1])

In [10]:
termination = Termination('evaluation_count')

In [11]:
CURR_FITNESS_EVALUATIONS = 0
is_solution = False
not(termination(
    curr_fitness_evaluations=CURR_FITNESS_EVALUATIONS,
    max_fitness_evaluations=config.MAX_FITNESS_EVALUATIONS,
    curr_iterations=0,  
    max_iterations=10000, 
    is_solution=is_solution
))


True

In [28]:
weighting_func = lambda x: pow(x, 2)
weighting_func(np.array([1,2,3])) / 14

array([0.07142857, 0.28571429, 0.64285714])

In [29]:
weighting_func = lambda x: pow(x, 2)
weighting_func(np.array([1,2,3]))

array([1, 4, 9])

In [41]:
np.array(fitness_vals)**5 / np.sum(np.array(fitness_vals)**5)

array([0.01389426, 0.0050943 , 0.0050943 , 0.0066756 , 0.00862724,
       0.01735247, 0.01101079, 0.00282698, 0.01101079, 0.01101079,
       0.01735247, 0.00862724, 0.00282698, 0.0050943 , 0.01101079,
       0.00862724, 0.0050943 , 0.03203235, 0.00382795, 0.00862724,
       0.01389426, 0.00862724, 0.0066756 , 0.00862724, 0.01101079,
       0.01389426, 0.01389426, 0.00862724, 0.01389426, 0.01101079,
       0.00282698, 0.0066756 , 0.02146734, 0.00862724, 0.01735247,
       0.00100101, 0.0050943 , 0.0066756 , 0.00144998, 0.02146734,
       0.01101079, 0.0066756 , 0.01389426, 0.00862724, 0.01101079,
       0.0066756 , 0.0066756 , 0.00282698, 0.00862724, 0.01101079,
       0.01735247, 0.01101079, 0.0050943 , 0.01389426, 0.00862724,
       0.00862724, 0.00382795, 0.02632826, 0.0050943 , 0.0066756 ,
       0.01101079, 0.00067085, 0.01101079, 0.00862724, 0.01101079,
       0.01101079, 0.00382795, 0.01389426, 0.00862724, 0.0066756 ,
       0.00144998, 0.01735247, 0.01735247, 0.00862724, 0.00100

In [37]:
np.sum(np.array(fitness_vals)**5)

21.552007487579584

In [51]:
arr = np.array([1,2,3,4])**2
arr

array([ 1,  4,  9, 16])

In [47]:
np.arange(len(arr))

array([0, 1, 2, 3])

In [48]:
len(arr)

4

In [22]:
arr1 = np.random.randint(1, 9, size=8)
arr1_b = hash(arr1.tobytes())
arr2 = arr1.copy()
arr2_b = hash(arr2.tobytes())

print(arr1_b == arr2_b)

True


In [24]:
print(arr1_b)
print(arr2_b)

7719086398839400104
7719086398839400104


In [27]:
dic = {}
dic[arr1_b] = 20

In [30]:
dic[arr2_b] = 21
dic

{7719086398839400104: 21}

In [31]:
dic

{7719086398839400104: 21}

In [33]:
arr = np.array([[1,2], [3,4]])
arr**2

[[1, 2], [3, 4]]

In [ ]:
arr